### ISSUE TITLE
[v1.5] Bug fixes + UGDG Review TODO

### ISSUE THREAD

**Issue by charlesgohck** [CS2103T-W09B2/main#102]
- [ ] Scenarios for User Guide
- [ ] Review User Guide
- [ ] Review Developer Guide
