### ISSUE TITLE
[v1.5] Sort for Tasks, Avatar for PersonCards

### ISSUE THREAD

**Issue by charlesgohck** [CS2103T-W09B2/main#107]
**Sort Command Enhancement**
- [x] SortCommand for tasks
- [x] JUnit tests for SortCommand for tasks
- [x] Update UGDG for SortCommand

**If Time Permits: Avatar**
- [x] Add avatars to PersonCard
- [x] JUnit tests for Avatar
- [x] Update UGDG for Avatar
