### ISSUE TITLE
[v1.5][BUGS + TODO] Bugs to Fix and Things to do for v1.5

### ISSUE THREAD

**Issue by charlesgohck** [CS2103T-W09B2/main#138]
- [x] Fix avatar issue persisting for multiple users if that users do not have valid URL
- [x] JUnit tests for avatar
- [x] Global Password in Model
- [x] Global lock and unlock
- [x] JUnit tests for Global Password Commands
- [x] Update User Guide and Developer Guide for Global Password Commands enhancement
- [x] Finalize portfolio
- [x] Collate code
- [ ] **Prepare for **demo****

**Comment by charlesgohck** [comment]
The changing of passwords persists in the preferences.json file until it is closed. Once it is closed everything reverts back to default. Any suggestions to fix this?
